# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../views/setup_wizard/setup_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IslandSetupWizard(object):
    def setupUi(self, IslandSetupWizard):
        IslandSetupWizard.setObjectName("IslandSetupWizard")
        IslandSetupWizard.setWindowModality(QtCore.Qt.WindowModal)
        IslandSetupWizard.resize(813, 540)
        IslandSetupWizard.setMinimumSize(QtCore.QSize(712, 540))
        IslandSetupWizard.setSizeGripEnabled(False)
        IslandSetupWizard.setModal(True)
        IslandSetupWizard.setWizardStyle(QtWidgets.QWizard.MacStyle)
        IslandSetupWizard.setOptions(QtWidgets.QWizard.NoBackButtonOnLastPage|QtWidgets.QWizard.NoBackButtonOnStartPage|QtWidgets.QWizard.NoCancelButton|QtWidgets.QWizard.NoDefaultButton)
        IslandSetupWizard.setTitleFormat(QtCore.Qt.AutoText)
        IslandSetupWizard.setSubTitleFormat(QtCore.Qt.AutoText)
        self.page_vbox_install_1 = QtWidgets.QWizardPage()
        self.page_vbox_install_1.setObjectName("page_vbox_install_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_vbox_install_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.page_vbox_install_1)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #011e4c")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.vbox_setup_output_console = QtWidgets.QTextBrowser(self.page_vbox_install_1)
        self.vbox_setup_output_console.setObjectName("vbox_setup_output_console")
        self.verticalLayout.addWidget(self.vbox_setup_output_console)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_path_to_vboxmanage = QtWidgets.QPushButton(self.page_vbox_install_1)
        self.button_path_to_vboxmanage.setEnabled(False)
        self.button_path_to_vboxmanage.setVisible(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/search"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_path_to_vboxmanage.setIcon(icon)
        self.button_path_to_vboxmanage.setIconSize(QtCore.QSize(32, 32))
        self.button_path_to_vboxmanage.setObjectName("button_path_to_vboxmanage")
        self.horizontalLayout.addWidget(self.button_path_to_vboxmanage)
        self.button_install_vbox = QtWidgets.QPushButton(self.page_vbox_install_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_install_vbox.sizePolicy().hasHeightForWidth())
        self.button_install_vbox.setSizePolicy(sizePolicy)
        self.button_install_vbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/download"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_install_vbox.setIcon(icon1)
        self.button_install_vbox.setIconSize(QtCore.QSize(32, 32))
        self.button_install_vbox.setObjectName("button_install_vbox")
        self.horizontalLayout.addWidget(self.button_install_vbox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        IslandSetupWizard.addPage(self.page_vbox_install_1)
        self.page_vm_install_2 = QtWidgets.QWizardPage()
        self.page_vm_install_2.setObjectName("page_vm_install_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_vm_install_2)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.page_vm_install_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #011e4c")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.vm_install_status_label = QtWidgets.QLabel(self.page_vm_install_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vm_install_status_label.setFont(font)
        self.vm_install_status_label.setStyleSheet("color: green")
        self.vm_install_status_label.setObjectName("vm_install_status_label")
        self.verticalLayout_5.addWidget(self.vm_install_status_label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.install_choice_label = QtWidgets.QLabel(self.page_vm_install_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.install_choice_label.setFont(font)
        self.install_choice_label.setObjectName("install_choice_label")
        self.verticalLayout_2.addWidget(self.install_choice_label)
        self.opt_vm_local = QtWidgets.QRadioButton(self.page_vm_install_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_vm_local.setFont(font)
        self.opt_vm_local.setObjectName("opt_vm_local")
        self.verticalLayout_2.addWidget(self.opt_vm_local)
        self.opt_download = QtWidgets.QRadioButton(self.page_vm_install_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opt_download.setFont(font)
        self.opt_download.setObjectName("opt_download")
        self.verticalLayout_2.addWidget(self.opt_download)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.magnet_link = QtWidgets.QLineEdit(self.page_vm_install_2)
        self.magnet_link.setVisible(False)
        self.magnet_link.setInputMask("")
        self.magnet_link.setObjectName("magnet_link")
        self.verticalLayout_5.addWidget(self.magnet_link)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.path_islands_vm = QtWidgets.QLineEdit(self.page_vm_install_2)
        self.path_islands_vm.setVisible(False)
        self.path_islands_vm.setText("")
        self.path_islands_vm.setReadOnly(True)
        self.path_islands_vm.setObjectName("path_islands_vm")
        self.horizontalLayout_4.addWidget(self.path_islands_vm)
        self.btn_select_islands_vm_path = QtWidgets.QPushButton(self.page_vm_install_2)
        self.btn_select_islands_vm_path.setVisible(False)
        self.btn_select_islands_vm_path.setObjectName("btn_select_islands_vm_path")
        self.horizontalLayout_4.addWidget(self.btn_select_islands_vm_path)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.vm_install_output_console = QtWidgets.QTextBrowser(self.page_vm_install_2)
        self.vm_install_output_console.setObjectName("vm_install_output_console")
        self.verticalLayout_5.addWidget(self.vm_install_output_console)
        self.lbl_timeout_msg = QtWidgets.QLabel(self.page_vm_install_2)
        self.lbl_timeout_msg.setStyleSheet("color: #ff8000")
        self.lbl_timeout_msg.setText("")
        self.lbl_timeout_msg.setObjectName("lbl_timeout_msg")
        self.verticalLayout_5.addWidget(self.lbl_timeout_msg)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.page_vm_install_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.data_folder_path = QtWidgets.QLineEdit(self.page_vm_install_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.data_folder_path.setFont(font)
        self.data_folder_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.data_folder_path.setText("")
        self.data_folder_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.data_folder_path.setReadOnly(True)
        self.data_folder_path.setPlaceholderText("")
        self.data_folder_path.setObjectName("data_folder_path")
        self.horizontalLayout_3.addWidget(self.data_folder_path)
        self.btn_select_data_path = QtWidgets.QPushButton(self.page_vm_install_2)
        self.btn_select_data_path.setObjectName("btn_select_data_path")
        self.horizontalLayout_3.addWidget(self.btn_select_data_path)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(self.page_vm_install_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("color: #555")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_install_islands = QtWidgets.QPushButton(self.page_vm_install_2)
        self.btn_install_islands.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_install_islands.sizePolicy().hasHeightForWidth())
        self.btn_install_islands.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_install_islands.setFont(font)
        self.btn_install_islands.setStyleSheet("height: 50px; width: 150px")
        self.btn_install_islands.setIcon(icon1)
        self.btn_install_islands.setIconSize(QtCore.QSize(32, 32))
        self.btn_install_islands.setObjectName("btn_install_islands")
        self.horizontalLayout_2.addWidget(self.btn_install_islands)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        IslandSetupWizard.addPage(self.page_vm_install_2)
        self.page_complete_3 = QtWidgets.QWizardPage()
        self.page_complete_3.setObjectName("page_complete_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_complete_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page_complete_3)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: green;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.page_complete_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        IslandSetupWizard.addPage(self.page_complete_3)

        self.retranslateUi(IslandSetupWizard)
        QtCore.QMetaObject.connectSlotsByName(IslandSetupWizard)

    def retranslateUi(self, IslandSetupWizard):
        _translate = QtCore.QCoreApplication.translate
        IslandSetupWizard.setWindowTitle(_translate("IslandSetupWizard", "Wizard"))
        self.label.setText(_translate("IslandSetupWizard", "Step 1 - Virtualbox setup"))
        self.vbox_setup_output_console.setHtml(_translate("IslandSetupWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.button_path_to_vboxmanage.setText(_translate("IslandSetupWizard", "Path to vboxmanage "))
        self.button_install_vbox.setText(_translate("IslandSetupWizard", "Download and isntall Virtualbox"))
        self.label_2.setText(_translate("IslandSetupWizard", "Step 2 - Islands virtual machine setup"))
        self.vm_install_status_label.setText(_translate("IslandSetupWizard", "Virtual machine not found... Let\'s install it."))
        self.install_choice_label.setText(_translate("IslandSetupWizard", "Please select one:"))
        self.opt_vm_local.setText(_translate("IslandSetupWizard", "I already have Islands virtual machine on this computer"))
        self.opt_download.setText(_translate("IslandSetupWizard", "I would like to download Islands virtual machine"))
        self.magnet_link.setPlaceholderText(_translate("IslandSetupWizard", "Paste magnet link here..."))
        self.path_islands_vm.setPlaceholderText(_translate("IslandSetupWizard", "Path to Islands VM file"))
        self.btn_select_islands_vm_path.setText(_translate("IslandSetupWizard", "Select Islands VM file"))
        self.label_5.setText(_translate("IslandSetupWizard", "Data folder: "))
        self.btn_select_data_path.setText(_translate("IslandSetupWizard", "Select"))
        self.label_6.setText(_translate("IslandSetupWizard", "*All chat history, metadata, keys and user settings  will be stored in the selected folder"))
        self.btn_install_islands.setText(_translate("IslandSetupWizard", "Install "))
        self.label_3.setText(_translate("IslandSetupWizard", "Setup complete!"))
        self.label_4.setText(_translate("IslandSetupWizard", "Press \"Done\" to exit setup wizard"))


import resources_rc
