# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\views\main_form\main_form.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 660)
        MainWindow.setMinimumSize(QtCore.QSize(800, 660))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/island128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.top_panel = QtWidgets.QWidget(self.centralWidget)
        self.top_panel.setMinimumSize(QtCore.QSize(42, 328))
        self.top_panel.setObjectName("top_panel")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.top_panel)
        self.horizontalLayout_11.setContentsMargins(11, 11, 0, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(25, 25, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.top_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(256, 256))
        self.label.setMaximumSize(QtCore.QSize(256, 256))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/icons/island256.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(-1, 2, 6, 24)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.islandStatusLabel = QtWidgets.QLabel(self.top_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.islandStatusLabel.sizePolicy().hasHeightForWidth())
        self.islandStatusLabel.setSizePolicy(sizePolicy)
        self.islandStatusLabel.setMaximumSize(QtCore.QSize(1965, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.islandStatusLabel.setFont(font)
        self.islandStatusLabel.setStyleSheet("")
        self.islandStatusLabel.setScaledContents(False)
        self.islandStatusLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.islandStatusLabel.setObjectName("islandStatusLabel")
        self.horizontalLayout_2.addWidget(self.islandStatusLabel)
        self.islandStatus = QtWidgets.QLabel(self.top_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.islandStatus.sizePolicy().hasHeightForWidth())
        self.islandStatus.setSizePolicy(sizePolicy)
        self.islandStatus.setMaximumSize(QtCore.QSize(1965, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.islandStatus.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.islandStatus.setFont(font)
        self.islandStatus.setStyleSheet("")
        self.islandStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.islandStatus.setObjectName("islandStatus")
        self.horizontalLayout_2.addWidget(self.islandStatus)
        self.lbl_loading = QtWidgets.QLabel(self.top_panel)
        self.lbl_loading.setMaximumSize(QtCore.QSize(16, 16))
        self.lbl_loading.setVisible(False)
        self.lbl_loading.setText("")
        self.lbl_loading.setScaledContents(True)
        self.lbl_loading.setObjectName("lbl_loading")
        self.horizontalLayout_2.addWidget(self.lbl_loading)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 14, 1, 0)
        self.horizontalLayout_8.setSpacing(24)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 8, 0, -1)
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_go_to_island = QtWidgets.QPushButton(self.top_panel)
        self.btn_go_to_island.setMinimumSize(QtCore.QSize(250, 70))
        self.btn_go_to_island.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_go_to_island.setFont(font)
        self.btn_go_to_island.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_go_to_island.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/key-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_go_to_island.setIcon(icon1)
        self.btn_go_to_island.setAutoDefault(False)
        self.btn_go_to_island.setDefault(False)
        self.btn_go_to_island.setFlat(False)
        self.btn_go_to_island.setObjectName("btn_go_to_island")
        self.verticalLayout_9.addWidget(self.btn_go_to_island)
        self.btn_admin = QtWidgets.QPushButton(self.top_panel)
        self.btn_admin.setMinimumSize(QtCore.QSize(250, 70))
        self.btn_admin.setMaximumSize(QtCore.QSize(250, 70))
        self.btn_admin.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/gear"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_admin.setIcon(icon2)
        self.btn_admin.setDefault(False)
        self.btn_admin.setFlat(False)
        self.btn_admin.setObjectName("btn_admin")
        self.verticalLayout_9.addWidget(self.btn_admin)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.groupBox = QtWidgets.QGroupBox(self.top_panel)
        self.groupBox.setEnabled(False)
        self.groupBox.setVisible(False)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.setup_required_reason = QtWidgets.QLabel(self.groupBox)
        self.setup_required_reason.setObjectName("setup_required_reason")
        self.horizontalLayout_5.addWidget(self.setup_required_reason)
        self.setup_required_icon = QtWidgets.QLabel(self.groupBox)
        self.setup_required_icon.setMaximumSize(QtCore.QSize(16, 16))
        self.setup_required_icon.setText("")
        self.setup_required_icon.setPixmap(QtGui.QPixmap(":/images/info"))
        self.setup_required_icon.setScaledContents(True)
        self.setup_required_icon.setObjectName("setup_required_icon")
        self.horizontalLayout_5.addWidget(self.setup_required_icon)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_launch_setup = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_launch_setup.sizePolicy().hasHeightForWidth())
        self.button_launch_setup.setSizePolicy(sizePolicy)
        self.button_launch_setup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_launch_setup.setStyleSheet("width: 120px; height: 30px")
        self.button_launch_setup.setIcon(icon2)
        self.button_launch_setup.setObjectName("button_launch_setup")
        self.horizontalLayout.addWidget(self.button_launch_setup)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addWidget(self.top_panel)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 16, -1, -1)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.grp_note_container = QtWidgets.QGroupBox(self.centralWidget)
        self.grp_note_container.setVisible(False)
        self.grp_note_container.setObjectName("grp_note_container")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.grp_note_container)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lbl_hint = QtWidgets.QLabel(self.grp_note_container)
        self.lbl_hint.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_hint.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_hint.setText("")
        self.lbl_hint.setWordWrap(True)
        self.lbl_hint.setObjectName("lbl_hint")
        self.horizontalLayout_10.addWidget(self.lbl_hint)
        self.btn_close_hint = QtWidgets.QPushButton(self.grp_note_container)
        self.btn_close_hint.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_close_hint.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/no"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close_hint.setIcon(icon3)
        self.btn_close_hint.setFlat(True)
        self.btn_close_hint.setObjectName("btn_close_hint")
        self.horizontalLayout_10.addWidget(self.btn_close_hint)
        self.horizontalLayout_9.addWidget(self.grp_note_container)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.launchIslandButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launchIslandButton.sizePolicy().hasHeightForWidth())
        self.launchIslandButton.setSizePolicy(sizePolicy)
        self.launchIslandButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/play"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.launchIslandButton.setIcon(icon4)
        self.launchIslandButton.setIconSize(QtCore.QSize(48, 48))
        self.launchIslandButton.setAutoDefault(False)
        self.launchIslandButton.setDefault(False)
        self.launchIslandButton.setFlat(False)
        self.launchIslandButton.setObjectName("launchIslandButton")
        self.verticalLayout_2.addWidget(self.launchIslandButton)
        self.launchMode = QtWidgets.QComboBox(self.centralWidget)
        self.launchMode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.launchMode.setObjectName("launchMode")
        self.launchMode.addItem("")
        self.launchMode.addItem("")
        self.verticalLayout_2.addWidget(self.launchMode)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.shutdownIslandButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutdownIslandButton.sizePolicy().hasHeightForWidth())
        self.shutdownIslandButton.setSizePolicy(sizePolicy)
        self.shutdownIslandButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shutdownIslandButton.setStyleSheet("padding: 15px")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/stop"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shutdownIslandButton.setIcon(icon5)
        self.shutdownIslandButton.setIconSize(QtCore.QSize(48, 48))
        self.shutdownIslandButton.setAutoDefault(False)
        self.shutdownIslandButton.setDefault(False)
        self.shutdownIslandButton.setFlat(False)
        self.shutdownIslandButton.setObjectName("shutdownIslandButton")
        self.verticalLayout_4.addWidget(self.shutdownIslandButton)
        self.stopMode = QtWidgets.QComboBox(self.centralWidget)
        self.stopMode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stopMode.setObjectName("stopMode")
        self.stopMode.addItem("")
        self.stopMode.addItem("")
        self.verticalLayout_4.addWidget(self.stopMode)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.restartIslandButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restartIslandButton.sizePolicy().hasHeightForWidth())
        self.restartIslandButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.restartIslandButton.setFont(font)
        self.restartIslandButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.restartIslandButton.setStyleSheet("padding: 20px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/reload"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartIslandButton.setIcon(icon6)
        self.restartIslandButton.setIconSize(QtCore.QSize(48, 48))
        self.restartIslandButton.setAutoDefault(False)
        self.restartIslandButton.setFlat(False)
        self.restartIslandButton.setObjectName("restartIslandButton")
        self.horizontalLayout_4.addWidget(self.restartIslandButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuKeys = QtWidgets.QMenu(self.menuBar)
        self.menuKeys.setObjectName("menuKeys")
        self.menuConfig = QtWidgets.QMenu(self.menuBar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setObjectName("actionExit")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setIconVisibleInMenu(True)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName("actionAbout")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionMinimize_2 = QtWidgets.QAction(MainWindow)
        self.actionMinimize_2.setObjectName("actionMinimize_2")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.act_islandsimage_authoring = QtWidgets.QAction(MainWindow)
        self.act_islandsimage_authoring.setObjectName("act_islandsimage_authoring")
        self.act_my_torrents = QtWidgets.QAction(MainWindow)
        self.act_my_torrents.setObjectName("act_my_torrents")
        self.act_trusted_keys = QtWidgets.QAction(MainWindow)
        self.act_trusted_keys.setObjectName("act_trusted_keys")
        self.act_my_keys = QtWidgets.QAction(MainWindow)
        self.act_my_keys.setObjectName("act_my_keys")
        self.act_open_config = QtWidgets.QAction(MainWindow)
        self.act_open_config.setObjectName("act_open_config")
        self.act_update_vm = QtWidgets.QAction(MainWindow)
        self.act_update_vm.setObjectName("act_update_vm")
        self.act_help = QtWidgets.QAction(MainWindow)
        self.act_help.setObjectName("act_help")
        self.act_view_logs = QtWidgets.QAction(MainWindow)
        self.act_view_logs.setObjectName("act_view_logs")
        self.menuOptions.addAction(self.actionInfo)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionMinimize_2)
        self.menuOptions.addAction(self.actionClose)
        self.menuTools.addAction(self.act_islandsimage_authoring)
        self.menuTools.addAction(self.act_my_torrents)
        self.menuKeys.addAction(self.act_trusted_keys)
        self.menuKeys.addAction(self.act_my_keys)
        self.menuConfig.addAction(self.act_open_config)
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.act_update_vm)
        self.menuConfig.addAction(self.act_view_logs)
        self.menuHelp.addAction(self.act_help)
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuKeys.menuAction())
        self.menuBar.addAction(self.menuConfig.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Island Manager"))
        self.islandStatusLabel.setText(_translate("MainWindow", "Island status: "))
        self.islandStatus.setText(_translate("MainWindow", "unknown"))
        self.btn_go_to_island.setText(_translate("MainWindow", "To Island!"))
        self.btn_admin.setText(_translate("MainWindow", "Admin"))
        self.setup_required_reason.setText(_translate("MainWindow", "Island VM not found"))
        self.button_launch_setup.setText(_translate("MainWindow", "Run setup"))
        self.grp_note_container.setTitle(_translate("MainWindow", "Note!"))
        self.launchIslandButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Launch island. </p></body></html>"))
        self.launchIslandButton.setText(_translate("MainWindow", "Launch Island"))
        self.launchMode.setItemText(0, _translate("MainWindow", "Quiet"))
        self.launchMode.setItemText(1, _translate("MainWindow", "Normal"))
        self.shutdownIslandButton.setText(_translate("MainWindow", "Shutdown Island"))
        self.stopMode.setItemText(0, _translate("MainWindow", "Soft"))
        self.stopMode.setItemText(1, _translate("MainWindow", "Force"))
        self.restartIslandButton.setText(_translate("MainWindow", "Restart Island"))
        self.menuOptions.setTitle(_translate("MainWindow", "Menu"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuKeys.setTitle(_translate("MainWindow", "Keys"))
        self.menuConfig.setTitle(_translate("MainWindow", "Config"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionMinimize_2.setText(_translate("MainWindow", "Minimize"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.act_islandsimage_authoring.setText(_translate("MainWindow", "Islands Image Authoring"))
        self.act_my_torrents.setText(_translate("MainWindow", "My torrents"))
        self.act_trusted_keys.setText(_translate("MainWindow", "Trusted keys"))
        self.act_my_keys.setText(_translate("MainWindow", "My keys"))
        self.act_open_config.setText(_translate("MainWindow", "Open configuration..."))
        self.act_update_vm.setText(_translate("MainWindow", "Update Islands VM..."))
        self.act_help.setText(_translate("MainWindow", "User guide"))
        self.act_view_logs.setText(_translate("MainWindow", "View logs"))


import resources_rc
