# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../views/import_key_form/import_key_form.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KeyImport(object):
    def setupUi(self, KeyImport):
        KeyImport.setObjectName("KeyImport")
        KeyImport.setWindowModality(QtCore.Qt.WindowModal)
        KeyImport.resize(656, 604)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(KeyImport)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_3.setSpacing(11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.key_password_label = QtWidgets.QLabel(KeyImport)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.key_password_label.setFont(font)
        self.key_password_label.setVisible(False)
        self.key_password_label.setStyleSheet("color: #444")
        self.key_password_label.setObjectName("key_password_label")
        self.verticalLayout_3.addWidget(self.key_password_label)
        self.new_password = QtWidgets.QLineEdit(KeyImport)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.new_password.setFont(font)
        self.new_password.setVisible(False)
        self.new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_password.setClearButtonEnabled(True)
        self.new_password.setObjectName("new_password")
        self.verticalLayout_3.addWidget(self.new_password)
        self.confirm_password = QtWidgets.QLineEdit(KeyImport)
        self.confirm_password.setVisible(False)
        self.confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password.setClearButtonEnabled(True)
        self.confirm_password.setObjectName("confirm_password")
        self.verticalLayout_3.addWidget(self.confirm_password)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(KeyImport)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #444")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.key_alias = QtWidgets.QLineEdit(KeyImport)
        self.key_alias.setObjectName("key_alias")
        self.verticalLayout_4.addWidget(self.key_alias)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ly_existing_password = QtWidgets.QVBoxLayout()
        self.ly_existing_password.setContentsMargins(-1, 10, -1, -1)
        self.ly_existing_password.setObjectName("ly_existing_password")
        self.is_key_encrypted = QtWidgets.QCheckBox(KeyImport)
        self.is_key_encrypted.setVisible(False)
        self.is_key_encrypted.setWhatsThis("")
        self.is_key_encrypted.setObjectName("is_key_encrypted")
        self.ly_existing_password.addWidget(self.is_key_encrypted)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.existing_password = QtWidgets.QLineEdit(KeyImport)
        self.existing_password.setVisible(False)
        self.existing_password.setStyleSheet("")
        self.existing_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.existing_password.setClearButtonEnabled(True)
        self.existing_password.setObjectName("existing_password")
        self.horizontalLayout_7.addWidget(self.existing_password)
        self.ly_existing_password.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.ly_existing_password)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(KeyImport)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(KeyImport)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("margin-top: 10px; margin-bottom: 5px; color: #444")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.import_from_file = QtWidgets.QRadioButton(KeyImport)
        self.import_from_file.setChecked(True)
        self.import_from_file.setObjectName("import_from_file")
        self.verticalLayout.addWidget(self.import_from_file)
        self.paste_as_plain_text = QtWidgets.QRadioButton(KeyImport)
        self.paste_as_plain_text.setObjectName("paste_as_plain_text")
        self.verticalLayout.addWidget(self.paste_as_plain_text)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(KeyImport)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.key_file_path = QtWidgets.QLineEdit(self.page)
        self.key_file_path.setReadOnly(False)
        self.key_file_path.setObjectName("key_file_path")
        self.horizontalLayout.addWidget(self.key_file_path)
        self.btn_select_file = QtWidgets.QPushButton(self.page)
        self.btn_select_file.setObjectName("btn_select_file")
        self.horizontalLayout.addWidget(self.btn_select_file)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ly_key_data = QtWidgets.QHBoxLayout()
        self.ly_key_data.setContentsMargins(-1, 15, -1, 15)
        self.ly_key_data.setObjectName("ly_key_data")
        self.key_data = QtWidgets.QPlainTextEdit(self.page_2)
        self.key_data.setVisible(True)
        self.key_data.setObjectName("key_data")
        self.ly_key_data.addWidget(self.key_data)
        self.verticalLayout_2.addLayout(self.ly_key_data)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 122, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_cancel = QtWidgets.QPushButton(KeyImport)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("color: #333; padding: 20px")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_4.addWidget(self.btn_cancel)
        self.btn_import = QtWidgets.QPushButton(KeyImport)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_import.setFont(font)
        self.btn_import.setStyleSheet("color: green; padding: 20px;")
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout_4.addWidget(self.btn_import)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)

        self.retranslateUi(KeyImport)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(KeyImport)

    def retranslateUi(self, KeyImport):
        _translate = QtCore.QCoreApplication.translate
        KeyImport.setWindowTitle(_translate("KeyImport", "Dialog"))
        self.key_password_label.setText(_translate("KeyImport", "Key password:"))
        self.new_password.setWhatsThis(_translate("KeyImport", "Every private key must be protected with password or passphrase. Please enter\n"
"                                    the password in this field. You will be required to enter it again every time you\n"
"                                    use this key.\n"
"                                "))
        self.new_password.setPlaceholderText(_translate("KeyImport", "Enter password for new key here..."))
        self.confirm_password.setPlaceholderText(_translate("KeyImport", "Confirm password"))
        self.label.setText(_translate("KeyImport", "Key alias:"))
        self.key_alias.setPlaceholderText(_translate("KeyImport", "Enter key alias (optional)"))
        self.is_key_encrypted.setText(_translate("KeyImport", "Private key is encrypted with password"))
        self.existing_password.setWhatsThis(_translate("KeyImport", "If imported private key is protected with password - enter the password\n"
"                                            here\n"
"                                        "))
        self.existing_password.setPlaceholderText(_translate("KeyImport", "Enter private key password"))
        self.label_2.setText(_translate("KeyImport", "How would you like to import your key?"))
        self.import_from_file.setText(_translate("KeyImport", "From file"))
        self.paste_as_plain_text.setText(_translate("KeyImport", "Paste as plain text"))
        self.key_file_path.setPlaceholderText(_translate("KeyImport", "Path to key file..."))
        self.btn_select_file.setText(_translate("KeyImport", "Select file..."))
        self.key_data.setPlaceholderText(_translate("KeyImport", "Paste key data here..."))
        self.btn_cancel.setText(_translate("KeyImport", "Cancel"))
        self.btn_import.setText(_translate("KeyImport", "Import!"))


