# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../views/config_form/config_form.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigForm(object):
    def setupUi(self, ConfigForm):
        ConfigForm.setObjectName("ConfigForm")
        ConfigForm.resize(1220, 581)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ConfigForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(ConfigForm)
        self.tabWidget.setObjectName("tabWidget")
        self.vm_config = QtWidgets.QWidget()
        self.vm_config.setObjectName("vm_config")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.vm_config)
        self.verticalLayout.setContentsMargins(8, 9, -1, -1)
        self.verticalLayout.setSpacing(33)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_vm_status_title = QtWidgets.QLabel(self.vm_config)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_vm_status_title.setFont(font)
        self.lbl_vm_status_title.setObjectName("lbl_vm_status_title")
        self.horizontalLayout_2.addWidget(self.lbl_vm_status_title)
        self.lbl_vm_name = QtWidgets.QLabel(self.vm_config)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_vm_name.setFont(font)
        self.lbl_vm_name.setStyleSheet("color: gray")
        self.lbl_vm_name.setObjectName("lbl_vm_name")
        self.horizontalLayout_2.addWidget(self.lbl_vm_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_refresh_info = QtWidgets.QPushButton(self.vm_config)
        self.btn_refresh_info.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_refresh_info.setStyleSheet("width: 150px; height: 20px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/reload"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_refresh_info.setIcon(icon)
        self.btn_refresh_info.setObjectName("btn_refresh_info")
        self.horizontalLayout_3.addWidget(self.btn_refresh_info)
        self.btn_update_vm = QtWidgets.QPushButton(self.vm_config)
        self.btn_update_vm.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_update_vm.setStyleSheet("width: 150px; height: 20px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/gear"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_update_vm.setIcon(icon1)
        self.btn_update_vm.setObjectName("btn_update_vm")
        self.horizontalLayout_3.addWidget(self.btn_update_vm)
        self.btn_select_vm = QtWidgets.QPushButton(self.vm_config)
        self.btn_select_vm.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_select_vm.setStyleSheet("width: 150px; height: 20px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/search"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_select_vm.setIcon(icon2)
        self.btn_select_vm.setObjectName("btn_select_vm")
        self.horizontalLayout_3.addWidget(self.btn_select_vm)
        self.btn_configure_data = QtWidgets.QPushButton(self.vm_config)
        self.btn_configure_data.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_configure_data.setStyleSheet("width: 150px; height: 20px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/import"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_configure_data.setIcon(icon3)
        self.btn_configure_data.setObjectName("btn_configure_data")
        self.horizontalLayout_3.addWidget(self.btn_configure_data)
        self.btn_del_vm = QtWidgets.QPushButton(self.vm_config)
        self.btn_del_vm.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_del_vm.setStyleSheet("width: 150px; height: 20px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/no"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del_vm.setIcon(icon4)
        self.btn_del_vm.setObjectName("btn_del_vm")
        self.horizontalLayout_3.addWidget(self.btn_del_vm)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.vm_info = QtWidgets.QTextBrowser(self.vm_config)
        self.vm_info.setObjectName("vm_info")
        self.verticalLayout.addWidget(self.vm_info)
        self.tabWidget.addTab(self.vm_config, "")
        self.misc = QtWidgets.QWidget()
        self.misc.setObjectName("misc")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.misc)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.vboxmanagePathLabel = QtWidgets.QLabel(self.misc)
        self.vboxmanagePathLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.vboxmanagePathLabel.setObjectName("vboxmanagePathLabel")
        self.horizontalLayout_11.addWidget(self.vboxmanagePathLabel)
        self.vboxmanagePathLineEdit = QtWidgets.QLineEdit(self.misc)
        self.vboxmanagePathLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.vboxmanagePathLineEdit.setObjectName("vboxmanagePathLineEdit")
        self.horizontalLayout_11.addWidget(self.vboxmanagePathLineEdit)
        self.vboxmanageSelectPath = QtWidgets.QPushButton(self.misc)
        self.vboxmanageSelectPath.setObjectName("vboxmanageSelectPath")
        self.horizontalLayout_11.addWidget(self.vboxmanageSelectPath)
        self.vboxmanageSave = QtWidgets.QPushButton(self.misc)
        self.vboxmanageSave.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/yes"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vboxmanageSave.setIcon(icon5)
        self.vboxmanageSave.setObjectName("vboxmanageSave")
        self.horizontalLayout_11.addWidget(self.vboxmanageSave)
        self.vboxmanageDefault = QtWidgets.QPushButton(self.misc)
        self.vboxmanageDefault.setIcon(icon)
        self.vboxmanageDefault.setObjectName("vboxmanageDefault")
        self.horizontalLayout_11.addWidget(self.vboxmanageDefault)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.misc, "")
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(ConfigForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigForm)

    def retranslateUi(self, ConfigForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigForm.setWindowTitle(_translate("ConfigForm", "Configuration"))
        self.lbl_vm_status_title.setText(_translate("ConfigForm", "Islands Virtual Machine:"))
        self.lbl_vm_name.setText(_translate("ConfigForm", "not configured"))
        self.btn_refresh_info.setText(_translate("ConfigForm", "Refresh info"))
        self.btn_update_vm.setText(_translate("ConfigForm", "Update / Replace"))
        self.btn_select_vm.setText(_translate("ConfigForm", "Select VM"))
        self.btn_configure_data.setText(_translate("ConfigForm", "Configure data folder"))
        self.btn_del_vm.setText(_translate("ConfigForm", "Delete current VM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vm_config), _translate("ConfigForm", "Islands VM configuration"))
        self.vboxmanagePathLabel.setText(_translate("ConfigForm", "Path to vboxmanage:"))
        self.vboxmanageSelectPath.setText(_translate("ConfigForm", "Browse..."))
        self.vboxmanageSave.setText(_translate("ConfigForm", "Save"))
        self.vboxmanageDefault.setText(_translate("ConfigForm", "Restore default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.misc), _translate("ConfigForm", "Miscellaneous"))


import resources_rc
